In [3]:
# Step 1: Install Required Libraries
# Run this cell to install the required libraries if not already installed
!pip install pandas textblob

# Step 2: Import Libraries
import pandas as pd
from textblob import TextBlob

# Step 3: Load the CSV File
# Replace 'your_file.csv' with the name of your CSV file
file_path = "C:\\Users\\Shree\\Downloads\\SA1.csv"
df = pd.read_csv(file_path)

# Step 4: Define a Function for Sentiment Analysis
def analyze_sentiment(comment):
    analysis = TextBlob(comment)
    if analysis.sentiment.polarity > 0:
        return "Positive"
    elif analysis.sentiment.polarity < 0:
        return "Negative"
    else:
        return "Neutral"

# Step 5: Perform Sentiment Analysis on the 3rd Column
# Assuming the 3rd column is index 2 (0-based indexing)
df['Emotion'] = df.iloc[:, 2].apply(analyze_sentiment)

# Step 6: Save the Results to a New CSV File
output_file = "sentiment_analysis_results.csv"
df.to_csv(output_file, index=False)

# Display the first few rows of the updated DataFrame
df.head()

Requirement already satisfied: pandas in c:\users\shree\anaconda3\lib\site-packages (1.5.3)
Requirement already satisfied: textblob in c:\users\shree\anaconda3\lib\site-packages (0.19.0)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\shree\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\shree\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in c:\users\shree\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: nltk>=3.9 in c:\users\shree\anaconda3\lib\site-packages (from textblob) (3.9.1)
Requirement already satisfied: click in c:\users\shree\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (8.0.4)
Requirement already satisfied: joblib in c:\users\shree\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\shree\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (2022.7.9)
Requirement already satisfied: tqdm in c:\users\shree\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (4.65.0)
Requirement already satisfied: six>=1.5 in c:\users\shree\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: colorama in c:\users\shree\anaconda3\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)

,Unnamed: 0.1,Unnamed: 0,Text,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour,Emotion
0,0,0,Enjoying a beautiful day at the park! ...,15-01-2023 12:30,User123,Twitter,#Nature #Park,15,30,USA,2023,1,15,12,Positive
1,1,1,Traffic was terrible this morning. ...,15-01-2023 08:45,CommuterX,Twitter,#Traffic #Morning,5,10,Canada,2023,1,15,8,Negative
2,2,2,Just finished an amazing workout! ðŸ’ª ...,15-01-2023 15:45,FitnessFan,Instagram,#Fitness #Workout,20,40,USA,2023,1,15,15,Positive
3,3,3,Excited about the upcoming weekend getaway! ...,15-01-2023 18:20,AdventureX,Facebook,#Travel #Adventure,8,15,UK,2023,1,15,18,Positive
4,4,4,Trying out a new recipe for dinner tonight. ...,15-01-2023 19:55,ChefCook,Instagram,#Cooking #Food,12,25,Australia,2023,1,15,19,Positive